services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=skyhigh
      - DB_PASSWORD=skyhigh123
      - DB_NAME=skyhigh
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # - JWT_SECRET=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJsb2NhbC1kZXYtdXNlciIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc3MjgxNTA4NywiZXhwIjoxNzcyOTAxNDg3fQ.4dckh9CJCPeiH6MEJJx_CcquKyXw18tgYgVCX4A1sbM
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: skyhigh
      POSTGRES_PASSWORD: skyhigh123
      POSTGRES_DB: skyhigh
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U skyhigh"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
